### ISSUE TITLE
ValueError: cannot reshape array of size 'x' into shape ('y', newaxis)

### ISSUE THREAD

**Issue by Leguark** [empymod/emg3d#126] opened 2020-07-27 09:13 UTC
Hi Dieter, congrats for the new release, seems to be a big one.

The example in gempy broke. I tried to just refactor the functions in utils but in the end I faced a reshaping error in the solution.
```
  File "C:/Users/legui/PycharmProjects/gempy/examples/integrations/gempy_discretize_emg3d.py", line 217, in <module>
    cgrid.plot_3d_slicer(
  File "C:\Users\legui\miniconda3\envs\gp-dev\lib\site-packages\discretize\View.py", line 830, in plot_3d_slicer
    tracker = Slicer(
  File "C:\Users\legui\miniconda3\envs\gp-dev\lib\site-packages\discretize\View.py", line 1421, in __init__
    self.v = mesh.r(v.reshape((mesh.nC, -1), order='F'), 'CC', 'CC', 'M')
ValueError: cannot reshape array of size 245440 into shape (237568,newaxis)
```

 So far I am fixing the version of emg3d to 0.11 for gempy so no rush

**Comment by prisae** [comment] 2020-07-27 10:33
The problem is a change in `discretize`, not in `emg3d`.

Easy fix: Just make sure you update discretize, it was fixed already (the problem is only 0.4.14).

Better fix: However, it will change eventually, so the BETTER fix is to change ` vType='Ex'` to ` v_type='Ex'` (it is an update to more PEP8-style namings, introduced in `0.4.14`)


I believe you already made these changes, right? (I thought I did them when I worked on it at Transform - my bad.)
```
- emg3d.utils.get_domain => emg3d.meshes.get_domain
- emg3d.utils.get_stretched_h => emg3d.meshes.get_stretched_h
- emg3d.utils.Model => emg3d.models.Model
- emg3d.utils.get_source_field => emg3d.fields.get_source_field
```

Sorry for any troubles, let me know how you get on.

**Comment by prisae** [comment] 2020-07-27 10:34
http://discretize.simpeg.xyz/en/master/release/0.4.14-notes.html

**Comment by prisae** [comment] 2020-08-20 05:51
@Leguark , can this be closed or does the issue remain?

**Comment by Leguark** [comment] 2020-08-20 07:09
I did not try recently. I have too many deadlines coming up next two weeks. I hope to start giving love to gempy again in mid september. 

Maybe we should close this issue and open one in gempy so I will not forget since now the ball is on my side

**Comment by prisae** [comment] 2020-08-20 08:21
That is fine. We'll keep it open, so I don't forget. Please just ping me (e.g. on Slack) if you get back to it, I am sure we can sort out this one within minutes together.

**Comment by prisae** [comment] 2020-12-03 20:14
@Leguark - I am closing this. There were a lot of updates recently to both `discretize` and `emg3d`, very likely you will encounter other problems. Please ping me if you need a hand updating the GemPy example, I am happy to do that.

Another option is to copy/paste from here: https://empymod.github.io/emg3d-gallery/gallery/interactions/GemPy-I.html

Tomorrow there will be a new `emg3d` release, to be compatible with `discretize>=0.6.0`. After that, everything should remain stable for much longer now :crossed_fingers:

**Closed by prisae** 2020-12-03 20:14 UTC
Labels: question

**Comment by Leguark** [comment] 2020-12-04 06:57
Oh cool! Having you an example I will just try to make a hyperlink to your documentations

**Comment by prisae** [comment] 2020-12-04 06:59
That might be  a good idea, so we don't have to keep updating both. And I guess you have enough with updating for all the other upstream stuff...

There are actually two examples:
- https://empymod.github.io/emg3d-gallery/gallery/interactions/GemPy-I.html
- https://empymod.github.io/emg3d-gallery/gallery/interactions/GemPy-II.html

I have to update the GemPy part in them though (I posted on #gempy in Slack, but I haven't looked in detail into it yet).
